# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b564fc19-d7f6-4fdc-b673-a858e2730043";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BB29-32D1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/203265df-6be0-48e0-adc3-829e547b663c";
      fsType = "btrfs";
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/d635080e-6231-472e-998c-5012262572aa";
      fsType = "btrfs";
      options = [ "subvol=games" ];
    };

  fileSystems."/mnt/steam-library" =
    { device = "/dev/disk/by-uuid/d635080e-6231-472e-998c-5012262572aa";
      fsType = "btrfs";
      options = [ "subvol=steam" ];
    };

  fileSystems."/mnt/backups" =
    { device = "/dev/disk/by-uuid/2c54d4c2-dbe6-4753-9f28-3e78ffd96d00";
      fsType = "btrfs";
      options = [ "subvol=backups" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/aaa5a52d-a07f-41f8-9020-527db8dd144e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
